# Generated by Django 5.1.4 on 2025-01-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_comments_courseenrollment_quizzes'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
