# Generated by Django 5.1.4 on 2025-01-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseenrollment_completed_delete_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='title',
            field=models.CharField(default='Knowledge Check', max_length=120),
        ),
    ]
