# Generated by Django 5.1.4 on 2025-01-02 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_quizzes_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.modules'),
            preserve_default=False,
        ),
    ]
