# Generated by Django 5.1.4 on 2025-01-02 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_lessons_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('resource_type', models.CharField(choices=[('PDF', 'PDF Document'), ('LINK', 'Web Link'), ('VIDEO', 'Video File'), ('IMAGE', 'Image File'), ('OTHER', 'Other File Type')], default='OTHER', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('link', models.URLField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.lessons')),
            ],
        ),
    ]
